name: flutter_supabase_integration
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  go_router: ^16.0.0
  riverpod: ^2.6.1
  shared_preferences: ^2.5.3
  supabase_flutter: ^2.9.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  app_links: ^3.4.5
  shimmer: ^3.0.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  freezed: ^2.4.7
  json_serializable: ^6.7.1

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
